/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Photos
 #	author : miyako
 #	2015/10/31
 #
 # --------------------------------------------------------------------------------*/

//#import "Photos.h"

#import <ScriptingBridge/ScriptingBridge.h>

@class PhotosApplication, PhotosMediaItem;

@interface PhotosApplication : SBApplication
- (SBElementArray *) mediaItems;
- (void) export:(SBElementArray *)x to:(NSURL *)to usingOriginals:(BOOL)usingOriginals;
@end

// A media item, such as a photo or video.
@interface PhotosMediaItem : SBObject

@property (copy) NSArray *keywords;  // A list of keywords to associate with a media item
@property (copy) NSString *name;  // The name (title) of the media item.
@property (copy) NSString *objectDescription;  // A description of the media item.
@property BOOL favorite;  // Whether the media item has been favorited.
@property (copy) NSDate *date;  // The date of the media item
- (NSString *) id;  // The unique ID of the media item
@property (readonly) NSInteger height;  // The height of the media item in pixels.
@property (readonly) NSInteger width;  // The width of the media item in pixels.
@property (copy, readonly) NSString *filename;  // The name of the file on disk.
@property (readonly) double altitude;  // The GPS altitude in meters.
@property (copy, readonly) NSArray *location;  // The GPS latitude and longitude, in an ordered list of 2 numbers.  Latitude in range -90.0 to 90.0, longitude in range -180.0 to 180.0.
- (PhotosMediaItem *) duplicate;  // Duplicate an object.  Only media items can be duplicated
@end

// --- Photos
void Photos_get_picture(sLONG_PTR *pResult, PackagePtr pParams);
